services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  laravel:
    build:
      context: ./Laravel
      dockerfile: Dockerfile
    volumes:
      - ./Laravel:/var/www/html
      # Mantener vendor en un volumen separado para evitar que el bind-mount
      # de la carpeta de proyecto en el host oculte la carpeta vendor creada
      # en la imagen o instalada dentro del contenedor.
      - laravel_vendor:/var/www/html/vendor
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

  react:
    build:
      context: ./React
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - laravel

volumes:
  db_data: {}
  laravel_vendor: {}
